### ISSUE TITLE
Reporting

### ISSUE THREAD

**Issue by mihuber** [ozagordi/VirMet#8]
- [x] NA in species list
- [ ] turn on/off reporting of human endogenous retroviruses
- [ ] mark usual suspects (HIV-2, choristoneura, uncultured marine virus) as contamination?

**Comment by ozagordi** [comment]
N/A in species list should be corrected with a correct updating of the databases. It should work now but we will see with time.

Endogenous retroviruses are reported because of an insufficient decontamination of human reads, I would keep them because it's also a sign of quality.

Usual suspects can also be a proxy to get how well we decontaminated and for this reason I would keep them (also, we might one day really sequence a HIV-2 sample).
